
spring:
  application:
    name: shopapp

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    expiryMinute: ${EXPIRY_MINUTE}
    expiryHour: ${EXPIRY_HOUR}
    expiryDay: 14
    accessKey: ${ACCESS_KEY}
    refreshKey: ${REFRESH_KEY}
  jpa:
    hibernate:
      ddl-auto: update  # Các giá trị có thể là none, create, update, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      smtp:
        auth: true
      mail:
        smtp:
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: file:///C:/Users/T/Desktop/images/
app:
  cors:
    allowed-origin: ${API_CROSS}
payment:
  vnpay:
    vnp_PayUrl: ${PAY_URL}
    vnp_TmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    vnp_ReturnUrl: ${RETURN_URL}
    vnp_Version: ${VERSION}
    vnp_Command: ${COMMAND}
    orderType: ${ORDER_TYPE}
debug: true

